projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4466"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
  # database:
  #   schemaPath: "src/database/datamodel.graphql"
  #   extensions:
  #     prisma: database/prisma.yml
